// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnUO3HRfYVTBqAGVx24CBy8Dk-SNJkhGk',
    appId: '1:832492437055:web:7094b295e4902e10ddc28a',
    messagingSenderId: '832492437055',
    projectId: 'ditonton-4dfde',
    authDomain: 'ditonton-4dfde.firebaseapp.com',
    storageBucket: 'ditonton-4dfde.appspot.com',
    measurementId: 'G-TPQ0C1K04L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOg0GBJQwISDFB0wvj-_QtDcEl3e5W04',
    appId: '1:832492437055:android:8f6e19ee8b669026ddc28a',
    messagingSenderId: '832492437055',
    projectId: 'ditonton-4dfde',
    storageBucket: 'ditonton-4dfde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJCnas8o9J-aJv_CVoQyQrEnuH8PM108',
    appId: '1:832492437055:ios:f4653a80af0fbc30ddc28a',
    messagingSenderId: '832492437055',
    projectId: 'ditonton-4dfde',
    storageBucket: 'ditonton-4dfde.appspot.com',
    iosClientId: '832492437055-ngf15em0kbuggbpc0iv60sr5m1i2goin.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
